<?php

namespace EthnoDoc\PublicationBundle\ElasticaRepository;

use FOS\ElasticaBundle\Repository;

/**
 * NonEditedMusicalNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElasticaNonEditedMusicalNoteRepository extends Repository
{
}
