imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: @EthnoDocPublicationBundle/Resources/config/services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: fr }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  fr
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Elastica Configuration
parameters:
    fos_elastica.logger.class: EthnoDoc\Elastica\DisabledElasticaLogger

fos_elastica:
    clients:
        default: { host: localhost, port: 9200}
    serializer:
        callback_class: FOS\ElasticaBundle\Serializer\Callback
        serializer: serializer
    indexes:
        ethnodoc:
            finder: ~
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            default:
                                tokenizer: keyword
                            custom_french_analyzer:
                                type: custom
                                tokenizer: letter
                                filter: ["asciifolding", "lowercase", "french_stem", "stop_fr"]
                            keylower:
                                tokenizer: keyword
                                filter: lowercase
                        filter:
                            stop_fr:
                                type: "stop"
                                stopwords: ["l", "m", "t", "qu", "n", "s", "j", "d"]
            types:
                EditedMusicalNote:
                    mappings:
                        title:
                            type: string
                            analyzer: keylower
                        date:
                            type: string
                            analyzer: keylower
                        language:
                            type: string
                            analyzer: keylower
                        url:
                            type: string
                            analyzer: keylower
                        type_document:
                            type: string
                            analyzer: keylower
                    persistence:
                        driver: orm
                        model: EthnoDoc\PublicationBundle\Entity\EditedMusicalNote
                        provider: ~
                        finder: ~
                        repository: EthnoDoc\PublicationBundle\ElasticaRepository\ElasticaEditedMusicalNoteRepository
                        listener: ~
                NonEditedMusicalNote:
                    mappings:
                        title:
                            type: string
                            analyzer: keylower
                        date:
                            type: string
                            analyzer: keylower
                        language:
                            type: string
                            analyzer: keylower
                        url:
                            type: string
                            analyzer: keylower
                        type_document:
                            type: string
                            analyzer: keylower
                    persistence:
                        driver: orm
                        model: EthnoDoc\PublicationBundle\Entity\NonEditedMusicalNote
                        provider: ~
                        finder: ~
                        repository: EthnoDoc\PublicationBundle\ElasticaRepository\ElasticaNonEditedMusicalNoteRepository
                        listener: ~
                HandWrittenNote:
                    mappings:
                        title:
                            type: string
                            analyzer: keylower
                        date:
                            type: string
                            analyzer: keylower
                        language:
                            type: string
                            analyzer: keylower
                        url:
                            type: string
                            analyzer: keylower
                        type_document:
                            type: string
                            analyzer: keylower
                    persistence:
                        driver: orm
                        model: EthnoDoc\PublicationBundle\Entity\HandWrittenNote
                        provider: ~
                        finder: ~
                        repository: EthnoDoc\PublicationBundle\ElasticaRepository\ElasticaHandWrittenNoteRepository
                        listener: ~
                IcoVideoGraphyNote:
                    mappings:
                        title:
                            type: string
                            analyzer: keylower
                        date:
                            type: string
                            analyzer: keylower
                        language:
                            type: string
                            analyzer: keylower
                        url:
                            type: string
                            analyzer: keylower
                        type_document:
                            type: string
                            analyzer: keylower
                    persistence:
                        driver: orm
                        model: EthnoDoc\PublicationBundle\Entity\IcoVideoGraphyNote
                        provider: ~
                        finder: ~
                        repository: EthnoDoc\PublicationBundle\ElasticaRepository\ElasticaIcoVideoGraphyNoteRepository
                        listener: ~
                SpokenArchiveNote:
                    mappings:
                        title:
                            type: string
                            analyzer: keylower
                        date:
                            type: string
                            analyzer: keylower
                        language:
                            type: string
                            analyzer: keylower
                        url:
                            type: string
                            analyzer: keylower
                        type_document:
                            type: string
                            analyzer: keylower
                    persistence:
                        driver: orm
                        model: EthnoDoc\PublicationBundle\Entity\SpokenArchiveNote
                        provider: ~
                        finder: ~
                        repository: EthnoDoc\PublicationBundle\ElasticaRepository\ElasticaSpokenArchiveNoteRepository
                        listener: ~
                RecipeNote:
                    mappings:
                        title:
                            type: string
                            analyzer: keylower
                        date:
                            type: string
                            analyzer: keylower
                        language:
                            type: string
                            analyzer: keylower
                        url:
                            type: string
                            analyzer: keylower
                        type_document:
                            type: string
                            analyzer: keylower
                    persistence:
                        driver: orm
                        model: EthnoDoc\PublicationBundle\Entity\RecipeNote
                        provider: ~
                        finder: ~
                        repository: EthnoDoc\PublicationBundle\ElasticaRepository\ElasticaRecipeNoteRepository
                        listener: ~