<?php

namespace EthnoDoc\PublicationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EditedMusicalNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditedMusicalNoteRepository extends EntityRepository
{
}
