<?php

namespace EthnoDoc\PublicationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IcoVideoGraphyNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IcoVideoGraphyNoteRepository extends EntityRepository
{
}
